### ISSUE TITLE
ImportError: cannot import name 'CachedCfFactory'

### ISSUE THREAD

**Issue by spencerh-b** [bitcraze/crazyflie-lib-python#72]
I don't understand why I am getting this error In the same line Swarm is detected fine, but never this class. It is so beyond me at this point I have never seen something like it.

**Comment by krichardsson** [comment]
The reason is probably that the CachedCfFactory class was added after the latest release of the lib so If you have pip installed the lib you will not find the class. The problem will be resolved as soon as we make the next release of the lib, not sure when this will happen though.

Until then just clone the repo and ```pip install -e path/to/your/cloned/cflib``` to run from the source in the repos instead.

**Comment by spencerh-b** [comment]
Thank you @krichardsson
